CICD2 Migration... and more
Saildrone/titiler pull request #11
Opened 2023-03-28 17:52 UTC by briansaildrone

This PR:
* migrates titiler to CICD2
* moves titiler to codeartifact
* moves titiler to a saildrone managed base image
* tests out some fancy new orb stuff such as tag suffixes
* omits the `/app` directory for the codebase, since this is a forked repo

a follow up PR will adjust the orb version, as the changes need to be tested against the full feature > main (sd-master in this case) deploy pipeline

2024-08-28 16:10 UTC, tcjennings requested changes
Please rebase these commits to a single commit (e.g., using `git rebase -i`) and consider changing the branch name to `sd-main`.

2024-08-28 16:10 UTC, tcjennings commented on Dockerfile
> +ARG BASE_IMAGE=026314688606.dkr.ecr.us-west-2.amazonaws.com/python:3.8
Please set the # syntax directive for buildkit frontend v1

2024-08-28 16:10 UTC, tcjennings commented on pyproject.toml
> +authors = ["Jeff Wang <jeff@saildrone.com>"]
Please set the authors field to a group instead of an individual.

2024-08-28 17:30 UTC, briansaildrone commented
@Toby Jennings ***@***.***>  can you handle the suggested
changes?
* Unsure what group y'all use
* I'm indifferent to branch and this is a data pipeline owned project
* you're the buildkit pro

Thanks!

*Brian Derdiarian*
Engineering Manager, Platform Infrastructure
Saildrone, Inc.
<https://streaklinks.com/BV1j40ENjZX2fpyXOw46M-K8/https%3A%2F%2Fwww.saildrone.com%2F>
1050 W. Tower Avenue Alameda, CA 94501

Follow us on social @saildrone!
FACEBOOK
<https://streaklinks.com/BV1j40IgIJdpmDN_JQ0mx0PT/https%3A%2F%2Fwww.facebook.com%2Fsaildrone>
 | TWITTER
<https://streaklinks.com/BV1j40I1tUfDF-wkqAXayBkq/https%3A%2F%2Ftwitter.com%2F%40saildrone>
 | LINKEDIN
<https://streaklinks.com/BV1j40EICIiqsCfyJwU1_30o/https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fsaildrone-inc%2F>
 | INSTAGRAM
<https://streaklinks.com/BV1j40I4OMPmD89N1gumojmz/https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fsaildrone-inc%2F>
 | YOUTUBE
<https://streaklinks.com/BV1j40EWFpBE3OybHAgXoVLA/https%3A%2F%2Fwww.youtube.com%2Fsaildrone>




On Wed, Aug 28, 2024 at 9:10 AM Toby Jennings ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Please rebase these commits to a single commit (e.g., using git rebase -i)
> and consider changing the branch name to sd-main.
> ------------------------------
>
> In Dockerfile
> <https://github.com/Saildrone/titiler/pull/11#discussion_r1734956750>:
>
> > @@ -1,6 +1,12 @@
> -ARG BASE_IMAGE=python:3.8.9-slim-buster
> +ARG BASE_IMAGE=026314688606.dkr.ecr.us-west-2.amazonaws.com/python:3.8
>
> Please set the # syntax directive for buildkit frontend v1
> ------------------------------
>
> In pyproject.toml
> <https://github.com/Saildrone/titiler/pull/11#discussion_r1734957701>:
>
> > @@ -0,0 +1,7 @@
> +[tool.poetry]
> +name = "titiler"
> +version = "0.1.0"
> +description = "Automated background task service."
> +authors = ["Jeff Wang ***@***.***>"]
>
> Please set the authors field to a group instead of an individual.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Saildrone/titiler/pull/11#pullrequestreview-2266719619>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANAGDOW3MOHLIXXAAC5J6RDZTXZA3AVCNFSM6AAAAABM6PW6K2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENRWG4YTSNRRHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-04 18:44 UTC, tcjennings approved these changes
That oughta do it for now

2024-09-04 19:25 UTC, alicehuang-saildrone approved these changes
Lgtm!

2024-09-04 20:12 UTC, merged